import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Message from '../components/message';
import { auth, db } from '../utils/firebase';
import Link from 'next/link';
import { useAuthState } from 'react-firebase-hooks/auth';

const Home = () => {

  const [posts, setPosts] = useState([]);
  const [user, loading] = useAuthState(auth);

  const getPosts = async () => {

    const collectionRef = collection(db, "posts"); // Posts Collection
    const q = query(collectionRef, orderBy("timestamp", "desc")); // Query => Get by timestamp

    const unsubscribe = onSnapshot(q, (snapshot) => {
      setPosts(snapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
      snapshot.docs.map((doc) => console.log(doc.data()));
    });

    return unsubscribe;
  }

  const signOut = () => {
    auth.signOut();
  }

  useEffect(() => {
    getPosts();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-12 text-lg font-medium">
        <h2>See what other people are saying</h2>
        {
          posts.map(post => (
            <Message key={post.id} {...post}>
              <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
                <button>
                  {post.comments?.length > 0 ? post.comments?.length : 0} comments
                </button>
              </Link>
            </Message>
          ))
        }
      </div>

      {
        user && (
          <div className="text-center my-5">
            <p className="text-md font-bold text-gray-500">{loading ? 'Loading' : user && user.displayName}</p>
            <button
              className="text-white bg-red-500 py-1 px-2 text-sm rounded-sm"
              onClick={signOut}>
              Sign Out
            </button>
          </div>
        )
      }
    </div>
  )
}

export default Home;